swagger: '2.0'
info:
  title: echo context variables
  x-ibm-name: echo-context-variables
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |+
            context.set("message.headers.content-type","application/json");
            var  list = context.list();
            list.request = context.get('request'); 
            list.system = context.get('system'); 
            list.session = context.get('session');
            list.env = context.get('env');
            list.policy = context.get('policy');
            list.message = context.get('message'); 
            list.api= context.get('api');
            list.client= context.get('client');
            list.plan= context.get('plan');

            context.message.body.write(list);

  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication: {}
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /day1/echo
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
schemes:
  - https
