swagger: '2.0'
info:
  title: set header using gatewayscript
  x-ibm-name: set-header-using-gatewayscript
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |

            context.set("message.headers.Content-Type","application/json");
             // oR
            context.message.header.set('Content-Type', "text/json");

            /************/
            context.set("message.headers.header2","h2");
              context.set("message.header.headerX","HX");//will not work as http header it wil create object called header on the message structure
             // oR
            context.message.header.set('header3', "h3");
             
             var  list = {};
             list.message = context.get('message'); 
             list.h2_using_header = context.message.header.get('header2');
              list.h3_using_headers = context.message.headers.header3;
            context.message.body.write(list);
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  application-authentication: {}
basePath: /day2/set-header-using-gatewayscript
paths:
  /:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    head:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
    patch:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
schemes:
  - https
